### ISSUE TITLE
Feature Suggestion: Basic file parsing to detect library usage

### ISSUE THREAD

**Issue by csrakowski** [sedouard/gittrack#100]
You mentioned you were interested in finding out what technology stacks people are using, but currently only have access to the file extension.
To detect the usage of React this is fine, but this doesn't help when you try to detect other technologies like Angular or Knockout.
I would like to suggest a feature where the file's contents would be parsed to try and sniff out some 'known thing' that strongly indicates the usage of the library.
For the initial version this could be as simple as a using regular expressions that sniffs for certain objects/methods. For example:

    angular.module()
    angular.controller()
    angular.directive()

and

    ko.computed()
    ko.observable()
    ko.applyBindings()

are strong indicators that Angular and Knockout are being used.

If you are interested, I'd be willing to write a start for it.

**Comment by sedouard** [comment]
Hey @csrakowski! This suggestion would be great from a UX perspective but I have some concerns:

- Parsing code is a pretty deep rabbit hole with lots languages and frameworks - I feel that it would be error prone and as brittle as scraping HTML from a web page. File extensions, as dumb as they are, are pretty stable, simple and fast to discern, at least at a basic level, what kind of code is in there.
- We would only be able to parse the commit diff, which could be good enough or not, I'm not sure. For example here's the contents of a commit - https://api.github.com/repos/sedouard/gittrack/commits/113a24e788f63531910bcea8b1269394b4db6767. We already load this data today and it sits in-memory. Downloading the entire code file would obviously be costly and we'd probably want to avoid that.

**Comment by csrakowski** [comment]
I agree with the first one; scraping is always a 'way to get the answer', but never a preferable long-term solution. Unfortunately I am not sure how else to implement this at the moment. We could eventually leverage something like Roslyn to detect library usage in C# and ASP.NET, but that seems a bit overkill for a V1/proof of concept. ;-)
I would like to borrow a concept from Roslyn's architecture though, and that is it's plugable nature. The central 'engine' would have access to the source file and would run a collection of analyzers on it. Each analyzer would then report back whether or not the code it was told about 'sniffed' like it's language/library.

Using this kind of architecture allows for easy plugin-in access to the detection features, and will allow us to easily refactor each individual analyzer to make use of whatever underlying technology it wants. For now this could simple regular expressions, but in the long run this might be a shell out to a full fledged compiler/linter.

I think a git diff will typically be too small to provide a good/strong indication and will probably result in a lot of misses. To put a number to this, I have 1 call to angular.module in a 1000 line .ts file, and that line has not changed since it was originally written over a year ago.
For now, and definitely for the proof-of-concept/architecture, the diff will just have to do. We can always add some logic later to download the entire file that changed in the commit (using the raw_url of the file).

If you are interested, I can probably find some time this week to make a good start on the architecture I described above and add a few simple analyzers.
Whether or not we need to add full file downloading, and whether or not that significantly impacts performance, will be a concern for a later day.

**Comment by sedouard** [comment]
Although you'll get some answers today by scraping, I don't like the idea since there isn't really anything in gittrack that wouldn't work in the future. Also, doing this kind of analysis within the GitTrack front-end isn't a very good idea.

As far as code analyzers go, there are plenty of sites that do in-browser interpretation of a variety of code. I'm not sure if there are any existing solutions. This would require running another backend service to do this work.

Using whole code files on the front-end (this repository) would be out of the question. Today, GitTrack is very XHR heavy. The github event stream and commits we analyze today already result in sometimes up to 100 xhr calls on startup. The load-time performance of the page is really important so that when you share the link it begins to work as soon as possible. To do this in a performant way would mean to generate this information on the back-end (ideally before the user even opens GitTrack.io) which would be much more work than I think it is worth. 

And I agree, using the diffs really isn't that useful.

Another problem with using full code files is that the person doing the commit is not necessarily responsible for *all* the code in that file. Example: I modify a code a line in an angular javascript file. Now GitTrack would count all parts of that code which use a stack or framework and attribute it to that person which may not actually be true.

The purpose of GitTrack is to quickly - at a high level - answer is what you have been working on, and the language/frameworks you use is part of that but it is a smaller part of that answer.

Although I really appreciate the offer to get started with the implementation of this, in general I think it would be overkill to engineer & maintain a solution that would do this for the value it yields (enhanced information the GitTrack languages chart).
